### ISSUE TITLE
handlebars template name for templates like "posts/index"?

### ISSUE THREAD

**Issue by inconduit** [icholy/ember-brunch#13]
i assume that the data-template-name for a handlebars template is inferred from the .hbs template file by brunch?

what about template names in the new ember router?  for example, a posts.index Route would have data-template-name="posts/index".  obviously a filename can't have a slash in it, so what would you name the .hbs file for that template?

**Comment by seankeating** [comment]
Brunch builds and defines the template name based on it's file location in the app folder.
So, /templates/anotherFolder/yetAnotherFolder/newHandleBarsFile.hbs would be defined as templates/anotherFolder/yetAnotherFolder/newHandleBarsFile

Since this doesn't work with the automatic route/template/etc matching that Ember does we define the 'templateName' in the view for the expected route so it knows where to get the template.

For your example you'd want to have a file/folder structure: templates/posts/index.hbs, but because brunch builds this with 'templates'  in the name, and so Ember itself won't find it.  So you will want to define it in the view as tempalateName: 'templates/posts/index.  The route would just be posts.index.

@icholy if we can make it so that it doesn't define compiled templates with 'templates' in the beginning we could take more advantage of the Ember automatic goodness, and eliminate the current implementation of views from the example.

**Comment by inconduit** [comment]
that makes sense, thank you kindly.  i was unable to find any of that information in the brunch.io docs, and this is the first time i've tried brunch.

**Comment by icholy** [comment]
@seankeating yeah that's a good idea.

**Comment by icholy** [comment]
I've update [ember-handlebars-brunch](https://github.com/icholy/ember-handlebars-brunch) to use [files.templates.root](https://github.com/icholy/ember-brunch/blob/master/config.coffee#L34) so this works now. I've went ahead and removed all the explicit controllers & views which get automatically generated.
